<a href="https://colab.research.google.com/github/robitussin/CCADMACL_EXERCISES/blob/main/Exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 1

Use all feature selection methods to find the best features

## Dataset Information

## Features

Number of Instances: 20640

Number of Attributes: 8 numeric, predictive attributes and the target

Attribute Information:

MedInc - median income in block group

HouseAge - median house age in block group

AveRooms - average number of rooms per household

AveBedrms - average number of bedrooms per household

Population - block group population

AveOccup - average number of household members

Latitude - block group latitude

Longitude - block group longitude

## Target
The target variable is the median house value for California districts, expressed in hundreds of thousands of dollars ($100,000).

In [45]:
from sklearn.datasets import fetch_california_housing
import pandas as pd

In [46]:
housing = fetch_california_housing(as_frame=True)
df = pd.concat([housing.data, housing.target], axis=1)
df_target = housing.target
df_features = housing.data

In [47]:
df.sample(4)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
8595,5.2999,33.0,6.050691,1.124424,561.0,2.585253,33.88,-118.38,3.594
7038,2.7647,20.0,4.109677,1.015054,1407.0,3.025806,33.96,-118.09,1.630
9834,4.3571,41.0,5.732240,1.081967,428.0,2.338798,36.63,-121.93,2.875
12148,2.0881,24.0,5.078408,1.109771,1283.0,1.547648,33.71,-117.20,0.833

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

1. Use any filter method to select the best features

In [48]:
# put your answer here
from sklearn.feature_selection import VarianceThreshold
threshold = 5
sl = VarianceThreshold(threshold=threshold)
s = sl.fit(df)

res = df.iloc[:, s.get_support()]
print("Filtered Method")
print("Filtered: ",res.columns)
print()
print("Original: ",df.columns)

Filtered Method
Filtered:  Index(['HouseAge', 'AveRooms', 'Population', 'AveOccup'], dtype='object')

Original:  Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude', 'MedHouseVal'],
      dtype='object')

2. Use any wrapper method to select the best features

In [55]:
# put your answer here
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import RFE

threshold = 5
rfr =RandomForestRegressor(n_estimators=200, random_state=0, max_depth=3)
sl = RFE(rfr, n_features_to_select=threshold, step=1 )

sl = sl.fit(df_features, df_target.values.ravel())
index = sl.get_support()
res = df_features.iloc[:, index]
print("Wrapper Method")
print("Wrapper: ",res.columns)
print()
print("Original: ",df.columns)

Wrapper Method
Wrapper:  Index(['MedInc', 'HouseAge', 'AveRooms', 'AveOccup', 'Latitude'], dtype='object')

Original:  Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude', 'MedHouseVal'],
      dtype='object')

3. Use any embedded methood to select the best features

In [56]:
# put your answer here
from sklearn.feature_selection import SelectFromModel
mrf = RandomForestRegressor(n_estimators=500, random_state=0, max_depth=3)
mrf = mrf.fit(df_features, df_target.values.ravel())

sfm = SelectFromModel(mrf, prefit=True)
index = sfm.get_support()

res = df_features.iloc[:, index]

In [57]:
print("Embedded Method")
print("Embedded: ",res.columns)
print()
print("Original: ",df.columns)

Embedded Method
Embedded:  Index(['MedInc', 'AveOccup'], dtype='object')

Original:  Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude', 'MedHouseVal'],
      dtype='object')